#!/bin/bash
# wp - simple script to null/enable WordPress readme.html and license.txt files on a cPanel server
# InterGen 5/12/15

function SEPARATOR {
tput setaf 3
tput bold
echo
echo "----------------------------"
echo
}
function BLOCK {
    if [ -f /home/"$USR"/public_html/readme.html ]; then
        SEPARATOR
        tput bold
        tput setaf 4
        echo "Checking account $USR"
        echo
        tput bold
        tput setaf 3
        echo "Blocking all 'readme.*' and 'license.*' files now..."
        sleep 1
        for identifier in $(find /home/"$USR"/public_html -type f -name "LICENSE.*" -o -name "license.*" -o -name "readme.*" -o -name "README.*"); 
do chown nobody:nobody "$identifier" && chmod 000 "$identifier"; done
        echo
        tput bold
        tput setaf 2
        echo "WordPress Indentifiers have been blocked for $USR."
        SEPARATOR
        tput sgr0
    else
        tput bold
        tput setaf 4
        echo "Checking WordPress Identifiers in account $USR"
        echo
        tput bold
        tput setaf 1
        echo "No readme.* or license.* files found, skipping $USR..."
        SEPARATOR
        tput sgr0
    fi
}
function UNBLOCK {
    if [ -f /home/"$USR"/public_html/readme.html ]; then
        SEPARATOR
        tput bold
        tput setaf 4
        echo "Checking account $USR"
        echo
        tput setaf 3
        echo "Unblocking 'readme.*' and 'license.*' files now..."
        sleep 1
        for identifier in $(find /home/"$USR"/public_html -type f -name "LICENSE.*" -o -name "license.*" -o -name "readme.*" -o -name "README.*"); 
do chown "$USR":"$USR" "$identifier" && chmod 644 "$identifier"; done
        echo
        tput bold
        tput setaf 2
        echo "WordPress Indentifiers have been unblocked for $USR."
        SEPARATOR
        tput sgr0
    else
        tput bold
        tput setaf 4
        echo "Checking account $USR"
        echo
        tput setaf 1
        echo "readme.html or license.txt not present, skipping $USR..."
        SEPARATOR
        tput sgr0
    fi
}
function ALL_USERS {
echo
echo
tput bold
tput setaf 2
echo -n "Ok, are we -1)Blocking or -2)Unblocking WordPress Identifiers [1/2]? "
old_stty_cfg=$(stty -g)
stty raw -echo
CHOICE=$( while ! head -c 1 | grep -i '[12]' ;do true ;done )
stty $old_stty_cfg
if echo "$CHOICE" | grep -iq "1" ;then
    printf "\n\n"
    for USR in $(grep \: /etc/userdomains | grep -v nobody | awk '{print $2}' | uniq); do BLOCK; done
else
    printf "\n\n"
    for USR in $(grep \: /etc/userdomains | grep -v nobody | awk '{print $2}' | uniq); do UNBLOCK; done
fi
}
function SINGLE_USER {
clear
echo 
echo
tput bold
tput setaf 2
echo
echo "--------------------------------------------------------"
echo
echo "Which account are we adjusting WordPress Identifiers for? "
SEPARATOR
grep \: /etc/userdomains | grep -v nobody | awk '{print $2}' | uniq
SEPARATOR
tput sgr0
echo -n "[enter account name]:"
read USR
if [ "$USR" != "$(grep "$USR" /etc/passwd | cut -d ':' -f 1)" ]; then
    echo
    SEPARATOR
    tput bold
    tput setaf 1 
    echo "That's not a valid user on this server Sparky, run it again..."
    echo
    tput bold
    tput setaf 4
    SEPARATOR
    tput bold
    tput setaf 3
    exit 1
else
    SEPARATOR
    tput bold
    tput setaf 2
    echo
    echo -n "Ok, are we 1)'Blocking' or 2)'Unblocking' WordPress Identifiers [1/2]? "
    old_stty_cfg=$(stty -g)
    stty raw -echo
    WHICH=$( while ! head -c 1 | grep -i '[12]' ;do true ;done )
    stty $old_stty_cfg
    if echo "$WHICH" | grep -iq "1" ;then
        printf "\n\n"
        BLOCK "$USR"
    else
        printf "\n\n"
        UNBLOCK "$USR"
    fi
fi
}
clear
echo
echo
tput bold
tput setaf 2
echo
echo "------------------------------------------------------------------"
echo
echo -n "Are we adjusting WordPress Identifiers for the entire server [y/n]? "
old_stty_cfg=$(stty -g)
stty raw -echo
answer="$( while ! head -c 1 | grep -i '[ny]' ;do true ;done )"
stty $old_stty_cfg
if echo "$answer" | grep -iq "^y" ;then
    echo
    ALL_USERS
else
    echo
    SINGLE_USER
fi
exit 0
