#!/bin/bash
# wp - simple script to null/enable WordPress readme.html and license.txt files on a cPanel server
# InterGen 5/12/15

function SEPARATOR {
tput setaf 3
tput bold
echo
echo "----------------------------"
echo
}
function BLOCK {
    if [ -f /home/"$USR"/public_html/readme.html ]; then
        tput bold
        tput setaf 4
        echo "Checking account $USR"
        echo
        tput bold
        tput setaf 3
        echo "Blocking all 'readme.*' and 'license.*' files now..."
        sleep 1
        for identifier in $(find /home/"$USR"/public_html -type f -name "LICENSE.*" -o -name "license.*" -o -name "readme.*" -o -name "README.*"); 
do chown nobody:nobody "$identifier" && chmod 000 "$identifier"; done
        echo
        tput bold
        tput setaf 2
        echo "WordPress Indentifiers have been blocked for $USR."
        SEPARATOR
        tput sgr0
    else
        tput bold
        tput setaf 4
        echo "Checking WordPress Identifiers in account $USR"
        echo
        tput bold
        tput setaf 1
        echo "No readme.* or license.* files found, skipping $USR..."
        SEPARATOR
        tput sgr0
    fi
}
function UNBLOCK {
    if [ -f /home/"$USR"/public_html/readme.html ]; then
        tput bold
        tput setaf 4
        echo "Checking account $USR"
        echo
        tput setaf 3
        echo "Unblocking 'readme.*' and 'license.*' files now..."
        sleep 1
        for identifier in $(find /home/"$USR"/public_html -type f -name "LICENSE.*" -o -name "license.*" -o -name "readme.*" -o -name "README.*"); 
do chown "$USR":"$USR" "$identifier" && chmod 644 "$identifier"; done
        echo
        tput bold
        tput setaf 2
        echo "WordPress Indentifiers have been unblocked for $USR."
        SEPARATOR
        tput sgr0
    else
        tput bold
        tput setaf 4
        echo "Checking account $USR"
        echo
        tput setaf 1
        echo "readme.html or license.txt not present, skipping $USR..."
        SEPARATOR
        tput sgr0
    fi
}
function ALL_USERS {
echo
echo
tput bold
tput setaf 2
echo -n "Ok, are we -1)Blocking or -2)Unblocking WordPress Identifiers [1/2]? "
read WHICH
echo
echo
if [ "$WHICH" = 1 ]; then
    echo
    for USR in $(grep \: /etc/userdomains | grep -v nobody | awk '{print $2}' | uniq); do BLOCK; done
    echo
else
    echo
    for USR in $(grep \: /etc/userdomains | grep -v nobody | awk '{print $2}' | uniq); do UNBLOCK; done
fi
}
function SINGLE_USER {
clear
echo 
echo
tput bold
tput setaf 2
echo
echo "--------------------------------------------------------"
echo
echo "Which account are we adjusting WordPress Identifiers for? "
SEPARATOR
grep \: /etc/userdomains | grep -v nobody | awk '{print $2}' | uniq
SEPARATOR
tput sgr0
echo -n "[enter account name]:"
read USR
if [ "$USR" != "$(grep "$USR" /etc/passwd | cut -d ':' -f 1)" ]; then
    echo
    SEPARATOR
    tput bold
    tput setaf 1 
    echo "That's not a valid user on this server Sparky, run it again..."
    echo
    tput bold
    tput setaf 4
    SEPARATOR
    tput bold
    tput setaf 3
    exit 1
else
    SEPARATOR
    tput bold
    tput setaf 2
    echo
    echo -n "Ok, are we -1)Blocking or -2)Unblocking WordPress Identifiers [1/2]? "
    read WHICH
    echo
    if [ "$WHICH" = 1 ]; then
        SEPARATOR
        echo
        BLOCK "$USR"
    else
        UNBLOCK "$USR"
    fi
fi
}

clear
echo
echo
tput bold
tput setaf 2
echo
echo "------------------------------------------------------------------"
echo
echo -n "Are we adjusting WordPress Identifiers for the entire server [y/N]? "
read SCOPE
if [ -z "$SCOPE" ]; then
    SINGLE_USER
else
    if [ "$SCOPE" = N ]; then
        SINGLE_USER
    else
        if [ "$SCOPE" = n ]; then
            SINGLE_USER
        else
            if [ "$SCOPE" = Y ]; then
                ALL_USERS
            else
                if [ "$SCOPE" = y ]; then
                    ALL_USERS
                else
                    SEPARATOR
                    tput bold
                    tput setaf 1
                    echo "That was a 'yes or no' question Sparky... run it again"
                    SEPARATOR
                    printf "\n\n"
                    exit 0
                fi
            fi
        fi
    fi
fi
exit 0
